services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=***
    volumes:
      - /c/Work/InterviewsPrep/HomeAssignment:/app/repo
      - /c/Users/david/.ssh:/root/.ssh
    command: sh -c "chmod 600 /root/.ssh/id_ed25519 && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

